11 fault polygon region
GNS-Science/opensha-ucerf3 pull request #16
Opened 2021-03-02 00:54 UTC by chrisbc

- various change in upstream classes for reuse / sub-classing in NSHM
 - merging Kevins work via upstream/master branch

2021-03-18 04:00 UTC, voj requested changes
A few remarks and questions. Also, we should clean up the git history before creating a pull request

2021-03-18 04:00 UTC, voj commented on src/scratch/UCERF3/griddedSeismicity/GridReader.java
> +		double offset = 0.0;
looks like this offset is not required

2021-03-18 04:00 UTC, voj commented on src/scratch/UCERF3/inversion/InversionTargetMFDs.java
> +	/**
this introduces a double-up that is addressed in merge-artifact commit. can be squashed.

2021-03-18 04:00 UTC, voj commented on src/scratch/UCERF3/griddedSeismicity/FaultPolyMgr.java
> +	private FaultPolyMgr setRegion(GriddedRegion region) {
Why are you using a private setter method? Wouldn't a constructor make more sense?

2021-03-18 04:00 UTC, voj commented on src/scratch/UCERF3/griddedSeismicity/FaultPolyMgr.java
> +	 * This method assumes that  of which references the polygon of it's parent fault.
I can't parse this sentence.

2021-03-18 04:00 UTC, voj commented on src/scratch/UCERF3/griddedSeismicity/GriddedSeisUtils.java
> +		this.pdf = pdf.clone();
on line 43, it's `getPDF()` instead of `clone()`. Should that be the same?

2021-03-18 04:00 UTC, voj commented on src/scratch/UCERF3/griddedSeismicity/GriddedSeisUtils.java
> +		this.pdf = pdf.clone();
I would also recommend to swap the order of the two lines to make it look more like the other constructor

2021-03-18 04:00 UTC, voj commented on src/scratch/UCERF3/griddedSeismicity/FaultPolyMgr.java
> +	private static GriddedRegion region;
should be merged with commit that makes this non-static

2021-03-18 04:00 UTC, voj commented on src/scratch/UCERF3/griddedSeismicity/FaultPolyMgr.java
> +	//= new CaliforniaRegions.RELM_TESTING_GRIDDED();
we don't need this comment

2021-03-18 04:00 UTC, voj commented on src/org/opensha/sha/earthquake/faultSysSolution/ruptures/plausibility/ScalarValuePlausibiltyFilter.java
>  		Preconditions.checkState(acceptableRange.hasLowerBound() || acceptableRange.hasUpperBound());
use better commit message

2021-03-18 04:00 UTC, voj commented on src/scratch/UCERF3/inversion/InversionFaultSystemRupSet.java
> +		init(rupSet); //CBC this needs to happen before the following helper methods
do we need this comment?

2021-03-25 01:28 UTC, chrisbc commented on src/scratch/UCERF3/griddedSeismicity/GridReader.java
> +		double offset = 0.0;
Yes - removed it.

2021-03-25 02:09 UTC, chrisbc commented on src/scratch/UCERF3/inversion/InversionFaultSystemRupSet.java
> +		init(rupSet); //CBC this needs to happen before the following helper methods
Agreed we're leaving this in for follow up on root cause..

2021-03-25 20:22 UTC, merged